name: workflow_dispatch sample 1

on:
  workflow_dispatch:

jobs:
  printLog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install swagger-cli
        run: npm install -g redoc-cli

      - name: Generate API doc
        run : redoc-cli bundle openapi.yaml -o index.html
